

INSERT INTO trades (
        user_id,
        pair_id,
        direction,
        entry_price,
        exit_price,
        stop_loss,
        take_profit,
        lot_size,
        profit_loss,
        opened_at,
        closed_at,
        status,
        strategy,
        timeframe,
        notes
    )
SELECT u.id,
    t.pair_id,
    t.direction,
    t.entry_price,
    t.exit_price,
    t.stop_loss,
    t.take_profit,
    t.lot_size,
    t.profit_loss,
    t.opened_at,
    t.closed_at,
    t.status,
    t.strategy,
    t.timeframe,
    t.notes
FROM users u
    CROSS JOIN (
        VALUES
            (
                1,
                'LONG',
                2028.50,
                2045.20,
                2015.00,
                2055.00,
                0.05,
                835.00,
                TIMESTAMP '2025-02-10 08:30:00',
                TIMESTAMP '2025-02-11 14:20:00',
                'CLOSED',
                'Breakout H4',
                'H4',
                'Seed : or, sortie partielle puis runner'
            ),
            (
                2,
                'SHORT',
                1.0850,
                1.0785,
                1.0920,
                1.0720,
                0.10,
                650.00,
                TIMESTAMP '2025-02-12 09:00:00',
                TIMESTAMP '2025-02-12 16:45:00',
                'CLOSED',
                'Mean reversion',
                'H1',
                'Seed : EUR/USD session Londres'
            ),
            (
                3,
                'LONG',
                1.2650,
                1.2580,
                1.2580,
                1.2750,
                0.08,
                -560.00,
                TIMESTAMP '2025-02-14 10:15:00',
                TIMESTAMP '2025-02-14 11:30:00',
                'CLOSED',
                'News fade',
                'M15',
                'Seed : GBP/USD stop touché'
            ),
            (
                4,
                'LONG',
                149.20,
                150.10,
                148.40,
                151.00,
                0.12,
                1080.00,
                TIMESTAMP '2025-02-18 07:00:00',
                TIMESTAMP '2025-02-19 22:00:00',
                'CLOSED',
                'Trend following',
                'D1',
                'Seed : USD/JPY carry'
            ),
            (
                5,
                'LONG',
                96500.00,
                101200.00,
                93800.00,
                105000.00,
                0.02,
                9400.00,
                TIMESTAMP '2025-02-20 12:00:00',
                TIMESTAMP '2025-02-22 09:30:00',
                'CLOSED',
                'Swing crypto',
                'H4',
                'Seed : BTC spot'
            ),
            (
                1,
                'LONG',
                2035.00,
                NULL,
                2010.00,
                2075.00,
                0.03,
                NULL,
                TIMESTAMP '2025-03-01 15:00:00',
                NULL,
                'OPEN',
                'Range play',
                'H1',
                'Seed : or en cours'
            ),
            (
                2,
                'SHORT',
                1.0820,
                NULL,
                1.0880,
                1.0720,
                0.06,
                NULL,
                TIMESTAMP '2025-03-02 11:20:00',
                NULL,
                'OPEN',
                'London breakout',
                'M30',
                'Seed : EUR/USD en attente'
            ),
            (
                5,
                'LONG',
                99500.00,
                NULL,
                97200.00,
                104000.00,
                0.01,
                NULL,
                TIMESTAMP '2025-03-03 08:45:00',
                NULL,
                'OPEN',
                'DCA léger',
                'D1',
                'Seed : BTC position ouverte'
            )
    ) AS t (
        pair_id,
        direction,
        entry_price,
        exit_price,
        stop_loss,
        take_profit,
        lot_size,
        profit_loss,
        opened_at,
        closed_at,
        status,
        strategy,
        timeframe,
        notes
    )
WHERE u.email = '__DEV_DEMO_EMAIL__'
    AND NOT EXISTS (
        SELECT 1
        FROM trades tr
        WHERE tr.user_id = u.id
    );
